# Generated by Django 2.2.4 on 2022-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsPart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='newType',
            field=models.CharField(choices=[('管理团队', '管理团队'), ('师资团队', '师资团队'), ('课程研发团队', '课程研发团队')], max_length=50, verbose_name='新闻类型'),
        ),
    ]
