# Generated by Django 2.2.4 on 2022-06-14 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' 社区标题')),
                ('description', models.TextField(verbose_name='社区详情描述')),
                ('productType', models.CharField(choices=[('足球新闻&小知识', '足球新闻&小知识'), ('体育英语', '体育英语'), ('体育相关政策', '体育相关政策'), ('健康知识', '健康知识')], max_length=50, verbose_name='社区类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='社区价格')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '社区',
                'verbose_name_plural': '社区',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='communityImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='community/', verbose_name='产品图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityImgs', to='communityPart.community', verbose_name='社区')),
            ],
            options={
                'verbose_name': '社区图片',
                'verbose_name_plural': '社区图片',
            },
        ),
    ]
