# Generated by Django 2.2.4 on 2022-06-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityPart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='productType',
            new_name='communityType',
        ),
        migrations.RenameField(
            model_name='communityimg',
            old_name='product',
            new_name='community',
        ),
    ]
