# Generated by Django 2.2.4 on 2022-06-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityPart', '0003_auto_20220615_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('-publishDate',), 'verbose_name': '社区', 'verbose_name_plural': '社区'},
        ),
        migrations.AlterModelOptions(
            name='communityimg',
            options={'verbose_name': '社区图片', 'verbose_name_plural': '社区图片'},
        ),
        migrations.AlterField(
            model_name='community',
            name='communityType',
            field=models.CharField(choices=[('足球新闻&小知识', '足球新闻&小知识'), ('足球英语', '足球英语'), ('体育相关政策', '体育相关政策'), ('健康知识', '健康知识')], max_length=50, verbose_name='社区类型'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(verbose_name='社区详情描述'),
        ),
        migrations.AlterField(
            model_name='community',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='社区发布量'),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=50, verbose_name=' 社区标题'),
        ),
        migrations.AlterField(
            model_name='communityimg',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityImgs', to='communityPart.community', verbose_name='社区'),
        ),
        migrations.AlterField(
            model_name='communityimg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='community/', verbose_name='社区图片'),
        ),
    ]
