# Generated by Django 3.2.7 on 2022-05-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='VideoIntro/')),
                ('video', models.FileField(blank=True, null=True, upload_to='VideoIntro/')),
            ],
        ),
    ]
