# Generated by Django 3.2.7 on 2022-06-13 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoPart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videointro',
            options={'ordering': ('-publishDate',), 'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AddField(
            model_name='videointro',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='videointro',
            name='title',
            field=models.CharField(default=' ', max_length=50, verbose_name='视频标题'),
        ),
        migrations.AlterField(
            model_name='videointro',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='videointro',
            name='photo',
            field=models.ImageField(blank=True, upload_to='VideoIntro/', verbose_name='视频封面图片'),
        ),
        migrations.AlterField(
            model_name='videointro',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='VideoIntro/', verbose_name='视频'),
        ),
    ]
