# Generated by Django 3.2.7 on 2022-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoPart', '0002_auto_20220613_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='videointro',
            name='videoType',
            field=models.CharField(choices=[('技术视频', '技术视频'), ('战术视频', '战术视频')], default='技术视频', max_length=50, verbose_name='视频类型'),
        ),
        migrations.AlterField(
            model_name='videointro',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='视频标题'),
        ),
    ]
