# Generated by Django 3.2.7 on 2022-06-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoPart', '0003_auto_20220613_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videointro',
            name='photo',
        ),
        migrations.CreateModel(
            name='VideoImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='VideoIntro/', verbose_name='视频封面')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoImgs', to='videoPart.videointro', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频封面',
                'verbose_name_plural': '视频封面',
            },
        ),
    ]
