# Generated by Django 3.2.7 on 2022-06-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoPart', '0002_auto_20220606_1001'),
        ('videoPart', '0004_auto_20220613_2208'),
    ]

    operations = [
    ]
