# Generated by Django 4.0.3 on 2022-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('家用机器人', '家用机器人'), ('智能监控', '智能监控'), ('人脸识别解决方案', '人脸识别解决方案')], max_length=50, verbose_name='产品类型'),
        ),
    ]
